### ISSUE TITLE
Invalid format for X-Auth Key header

### ISSUE THREAD

**Issue by darox** [lablabs/cloudflare-exporter#45]
I have installed the exporter via helmfile. 

`helmfile apply`

With content:

```
repositories: 
  - name: "cloudflare-exporter"
    url: "https://lablabs.github.io/cloudflare-exporter"

releases:
  - name: "cloudflare-exporter"
    namespace: "monitoring"
    version: "0.0.3"
    chart: "cloudflare-exporter/cloudflare-exporter"
    wait: true
    values:
      - env:
        - name: CF_API_KEY
          value: R**
        - name: CF_API_EMAIL
          value: ma*
        # Optionally select zones
        # - name: CF_ZONES
        #   value: "<zone_id1>,<zone_id2>,..."
        # DEPRICATED Optionally, you can filter zones by their adding IDs following the example below.
        # - name: ZONE_XYZ
        #   value: <zone_id>

```

The pods are crashing due to:

```
time="2021-10-16 15:39:37" level=info msg="Beginning to serve on port :8080"
time="2021-10-16 15:39:38" level=fatal msg="error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":6003,\\\"message\\\":\\\"Invalid request headers\\\",\\\"error_chain\\\":[{\\\"code\\\":6103,\\\"message\\\":\\\"Invalid format for X-Auth-Key header\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\""
```

The API key has read access to any resource in my CF account.  THis is where I got it from:
![image](https://user-images.githubusercontent.com/9934402/137593722-07495241-d381-498d-b435-f192b0a4268a.png)

Do you know anything about this particular issue?
