### ISSUE TITLE
securityContext not populated

### ISSUE THREAD

**Issue by darox** [lablabs/cloudflare-exporter#62]
While installing Cloudflare-Exporter via Helm-Chart and helmfile:

```
repositories: 
  - name: "cloudflare-exporter"
    url: "https://lablabs.github.io/cloudflare-exporter"


environments:
  default:
    values:
      - cloudflareexporter:
          key: ref+sops://secrets.yaml?format=yaml#/secrets/cloudflareexporter/key

releases:
  - name: "cloudflare-exporter"
    namespace: "monitoring"
    version: "0.1.8"
    chart: "cloudflare-exporter/cloudflare-exporter"
    wait: true
    values:
      - env:
        - name: CF_API_TOKEN
          value:  {{ .Values.cloudflareexporter.key | fetchSecretValue }} 
        - name: CF_API_EMAIL
          value: <mail>
        - name: CF_ZONES
          value: <zone>
      - name: securityContext.allowPrivilegeEscalation
        value: false
      - name: securityContext.runAsNonRoot
        value: true
      - name: securityContext.runAsUser
        value: 1000
      - name: securityContext.readOnlyRootFilesystem
        value: true
      - name: securityContext.capabilities.drop[0]
        value: ALL

```

it seems that securityContext are not populated:
```
monitoring, cloudflare-exporter, Deployment (apps) has been added:
- 
+ # Source: cloudflare-exporter/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: cloudflare-exporter
+   labels:
+     helm.sh/chart: cloudflare-exporter-0.1.8
+     app.kubernetes.io/name: cloudflare-exporter
+     app.kubernetes.io/instance: cloudflare-exporter
+     app.kubernetes.io/version: "0.0.9"
+     app.kubernetes.io/managed-by: Helm
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: cloudflare-exporter
+       app.kubernetes.io/instance: cloudflare-exporter
+   template:
+     metadata:
+       labels:
+         app.kubernetes.io/name: cloudflare-exporter
+         app.kubernetes.io/instance: cloudflare-exporter
+     spec:
+       securityContext:
+         {}
+       serviceAccountName: default
+       containers:
+         - name: cloudflare-exporter
+           securityContext:
+             {}
+           image: "ghcr.io/lablabs/cloudflare_exporter:0.0.9"
+           imagePullPolicy: Always
+           ports:
+             - name: http
+               containerPort: 8080
+               protocol: TCP
+           resources:
+             {}
+           env:
+             - name: CF_API_TOKEN
+               value: <token>
+             - name: CF_API_EMAIL
+               value:  <mail>
+             - name: CF_ZONES
+               value: <zone>
monitoring, cloudflare-exporter, Service (v1) has been added:
- 
+ # Source: cloudflare-exporter/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: cloudflare-exporter
+   labels:
+     helm.sh/chart: cloudflare-exporter-0.1.8
+     app.kubernetes.io/name: cloudflare-exporter
+     app.kubernetes.io/instance: cloudflare-exporter
+     app.kubernetes.io/version: "0.0.9"
+     app.kubernetes.io/managed-by: Helm
+   annotations:
+     prometheus.io/scrape: "true"
+ spec:
+   type: ClusterIP
+   ports:
+     - port: 8080
+       targetPort: http
+       protocol: TCP
+       name: http
+   selector:
+     app.kubernetes.io/name: cloudflare-exporter
+     app.kubernetes.io/instance: cloudflare-exporter
```

According to the values.yaml file, it should be possible to populate these values.
