### ISSUE TITLE
No CF Metrics after setup

### ISSUE THREAD

**Issue by caesartcs** [lablabs/cloudflare-exporter#66]
Hi, thank you for this tool but I am having a problem

**Free Plan** only
**CF Token** is Read only to Zone analytics, **also tried a Read Only to ALL Resources**
I am using docker-compose to run the image, Prometheus and Grafana also on docker-compose too.
```
cloudflare-exporter:
    image: lablabs/cloudflare_exporter
    container_name: cloudflare-exporter
    environment:
      - CF_API_TOKEN=*****
      - CF_ZONES=***.com,***.org
      - listen=:9102
      - free_tier=true
      - CF_API_KEY=*****
      - CF_API_EMAIL=***
    restart: unless-stopped
    ports:
      - "9102:8080"
```

Everything starts up fine and there is metrics showing at `dockerhost:9102/metrics`, and Prometheus is successfully scraping the job. However the metrics shown are only some system metrics and **NO cloudflare metrics at all**. Please see below:
```
...
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes -1
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 57
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```
That's it

I've tried with both Token only and with API Key and Email. Again, everything seems to work, but I am just not getting any cloudflare metrics to show up. Any idea?
