### ISSUE TITLE
For non enterprise zone doesn't collect metrics

### ISSUE THREAD

**Issue by rmalenko** [lablabs/cloudflare-exporter#84]
I have metrics for all enterprise zones, but non-enterprise (free) zones don't collect metrics.

My docker config is:
```yaml
docker_image_name: "lablabs/cloudflare_exporter"
    # docker_image_tag: "latest"
    docker_image_tag: "0.0.14"
    docker_container_name: "cloudflare_exporter"
    docker_container_env: {
      CF_API_TOKEN: "{{ cloudflare_token }}",
      SCRAPE_DELAY: "300s",
    }
    docker_container_published_ports: [ 8883:8080 ]
```

This [issue](https://github.com/lablabs/cloudflare-exporter/issues/47) looks as related.
